export const FETCH_ALL_LIKES_REQUEST = 'FETCH_ALL_LIKES_REQUEST';
export const FETCH_ALL_LIKES_SUCCESS = 'FETCH_ALL_LIKES_SUCCESS';
export const FETCH_ALL_LIKES_ERROR   = 'FETCH_ALL_LIKES_ERROR';

export const CLICK_LIKE_REQUEST = 'CLICK_LIKE_REQUEST';
export const CLICK_LIKE_SUCCESS = 'CLICK_LIKE_SUCCESS';
export const CLICK_LIKE_ERROR   = 'CLICK_LIKE_ERROR';
